### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by Travis-S**
fixed spelling error

### CODE REVIEW

**Comment by emptymalei** [comment]
Thank you. I guess I need to pay attention to the spelling.

**Comment by Travis-S** [comment]
I was mostly just trying to figure out how the heck PR on github works.

**Comment by emptymalei** [comment]
@Travis-S Now you see. :smile_cat:

**Comment by emptymalei** [comment]
@Travis-S Actually what you can do is to set up a pull request in your own project through different branches. :smiley_cat:

**Pull request merged**
